# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'birkelime_birislem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import ui.img_rc
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 205)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/imperial-logo.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)  # type: ignore
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_sayi_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_1.setEnabled(False)
        self.le_sayi_1.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_1.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_1.setPlaceholderText("")
        self.le_sayi_1.setObjectName("le_sayi_1")
        self.horizontalLayout.addWidget(self.le_sayi_1)
        self.le_sayi_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_2.setEnabled(False)
        self.le_sayi_2.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_2.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_2.setObjectName("le_sayi_2")
        self.horizontalLayout.addWidget(self.le_sayi_2)
        self.le_sayi_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_3.setEnabled(False)
        self.le_sayi_3.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_3.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_3.setObjectName("le_sayi_3")
        self.horizontalLayout.addWidget(self.le_sayi_3)
        self.le_sayi_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_4.setEnabled(False)
        self.le_sayi_4.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_4.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_4.setObjectName("le_sayi_4")
        self.horizontalLayout.addWidget(self.le_sayi_4)
        self.le_sayi_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_5.setEnabled(False)
        self.le_sayi_5.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_5.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_5.setObjectName("le_sayi_5")
        self.horizontalLayout.addWidget(self.le_sayi_5)
        self.le_sayi_10unkati = QtWidgets.QLineEdit(self.centralwidget)
        self.le_sayi_10unkati.setEnabled(False)
        self.le_sayi_10unkati.setMinimumSize(QtCore.QSize(0, 30))
        self.le_sayi_10unkati.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_sayi_10unkati.setAlignment(
            QtCore.Qt.AlignCenter)  # type: ignore
        self.le_sayi_10unkati.setObjectName("le_sayi_10unkati")
        self.horizontalLayout.addWidget(self.le_sayi_10unkati)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            45, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            195, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.le_hedeflenen_sayi = QtWidgets.QLineEdit(self.centralwidget)
        self.le_hedeflenen_sayi.setEnabled(False)
        self.le_hedeflenen_sayi.setMinimumSize(QtCore.QSize(0, 30))
        self.le_hedeflenen_sayi.setAlignment(
            QtCore.Qt.AlignCenter)  # type: ignore
        self.le_hedeflenen_sayi.setObjectName("le_hedeflenen_sayi")
        self.horizontalLayout_2.addWidget(self.le_hedeflenen_sayi)
        spacerItem2 = QtWidgets.QSpacerItem(
            47, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_hepsini_temizle = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hepsini_temizle.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_hepsini_temizle.setObjectName("btn_hepsini_temizle")
        self.verticalLayout_2.addWidget(self.btn_hepsini_temizle)
        self.btn_rasgele_sayi_uret = QtWidgets.QPushButton(self.centralwidget)
        self.btn_rasgele_sayi_uret.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_rasgele_sayi_uret.setObjectName("btn_rasgele_sayi_uret")
        self.verticalLayout_2.addWidget(self.btn_rasgele_sayi_uret)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_hesapla = QtWidgets.QPushButton(self.centralwidget)
        self.btn_hesapla.setMinimumSize(QtCore.QSize(0, 55))
        self.btn_hesapla.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btn_hesapla.setObjectName("btn_hesapla")
        self.horizontalLayout_4.addWidget(self.btn_hesapla)
        self.le_islemler = QtWidgets.QLineEdit(self.centralwidget)
        self.le_islemler.setEnabled(False)
        self.le_islemler.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.le_islemler.setFont(font)
        self.le_islemler.setAlignment(QtCore.Qt.AlignCenter)  # type: ignore
        self.le_islemler.setObjectName("le_islemler")
        self.horizontalLayout_4.addWidget(self.le_islemler)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 774, 31))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Bir İşlem @OnCaDo"))
        self.label_2.setText(_translate(
            "MainWindow", "Ulaşılmak İstenilen Sayı:"))
        self.btn_hepsini_temizle.setToolTip(_translate(
            "MainWindow", "Ekrandaki verileri temizler."))
        self.btn_hepsini_temizle.setText(
            _translate("MainWindow", "Hepsini Temizle"))
        self.btn_rasgele_sayi_uret.setToolTip(_translate(
            "MainWindow", "Rasgele yeni sayılar üretir ve ekranda gösterir."))
        self.btn_rasgele_sayi_uret.setText(
            _translate("MainWindow", "Sayıları Değiştir"))
        self.btn_hesapla.setToolTip(_translate(
            "MainWindow", "Hesaplamaları yapar ve istenilen sayıya ulaşmaya çalışır."))
        self.btn_hesapla.setText(_translate("MainWindow", "Hesapla"))
        self.btn_hesapla.setShortcut(_translate("MainWindow", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
